server:
  port: 8123

spring:
  application:
    name: abilities-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:6603/pokedexdb?allowPublicKeyRetrieval=true&useSSL=false
    username: dockeruser
    password: mypass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hbm2ddl:
          auto: none
        temp:
          '[use_jdbc_metadata_defaults]': false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
